QPPA-7889: Update Node from v10 to v18; update additional packages
CMSgov/qpp-shared-logger-node pull request #51
Opened 2023-07-19 17:46 UTC by john-manack

https://jira.cms.gov/browse/QPPA-7889

## Description

This ticket was originally opened to bump the npm package `moment`. However, since node v10 dropped security support in [April of 2021](https://endoflife.date/nodejs), it seemed like that should be prioritized as well. On top of this, the test suite was failing out-of-the-box at `master` branch without updating node.

Therefore, this PR updates node (v10 -> v18), and also updates various packages in package.json. In order to make sure there were no breaking changes as a result of these updates, the following steps were taken:

1. Ensure tests suite passes without errors
2. Ensure all package.json scripts run as expected.
3. Use the `npm link` tool to import the updated `qpp-shared-logger-node` package in the Submissions API and run that API's test suite to make sure the npm package still runs as expected.

## How Has This Been Tested?

See description above

## Screenshots (if appropriate):

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Updated documentation (`README.md`, etc.) depending if the changes require it.

2023-07-19 18:49 UTC, KyleApfel submitted a review, later dismissed
Great work! Thank you John. ⭐️

2023-07-19 20:01 UTC, nicholas-gates requested changes

2023-07-19 20:01 UTC, nicholas-gates commented on src/index.ts
> +    return { ...info, timestamp: localTimestamp() };
What is the reason for this change?

2023-07-21 18:24 UTC, nicholas-gates requested changes

2023-07-21 18:24 UTC, nicholas-gates commented on src/index.ts
> +    return { ...info, timestamp: localTimestamp() };
Thinking through this in my head: I think this function should be returning a winston format object and not a JSON object. The returned value gets combined with other winston formats to create an aggregate of all allowed formats. The JSON object won't be recognized as valid at that stage.

2023-07-21 19:18 UTC, nicholas-gates approved these changes

2023-07-21 19:20 UTC, merged